name: AWS Terraform Pipeline

on:
  workflow_dispatch:   # Manual trigger
  push:
    branches:
      - main           # Runs on push to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Needed for OIDC
      contents: read    # Needed to checkout repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::AccountNumber:role/github-deploy-role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6   # You can change to match your local version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
